/// Copyright (c) 2015-present, salesforce.com, inc. All rights reserved
/// Licensed under BSD 3-Clause - see LICENSE.txt or git.io/sfdc-license

package com.salesforce.designsystem;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.Drawable;

/**
 * Utility for generating Bitmaps from SLDS icons.
 */

public abstract class Icons {

    public static Bitmap getBitmap(Context context, ActionIcons icon, int size) {
        return getBitmap(context, icon, size, context.getResources().getColor(R.color.slds_color_text_icon_default));
    }

    public static Drawable getDrawable(Context context, ActionIcons icon, int size) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size));
    }

    public static Bitmap getBitmap(Context context, ActionIcons icon, int size, int color) {
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bmp);

        drawIconGlyph(context, icon.value, size, canvas, color);

        return bmp;
    }

    public static Drawable getDrawable(Context context, ActionIcons icon, int size, int color) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size, color));
    }

    public static Bitmap getBitmap(Context context, CustomIcons icon, int size) {
        return getBitmap(context, icon, size, context.getResources().getColor(R.color.slds_color_text_icon_default));
    }

    public static Drawable getDrawable(Context context, CustomIcons icon, int size) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size));
    }

    public static Bitmap getBitmap(Context context, CustomIcons icon, int size, int color) {
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bmp);

        drawIconGlyph(context, icon.value, size, canvas, color);

        return bmp;
    }

    public static Drawable getDrawable(Context context, CustomIcons icon, int size, int color) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size, color));
    }

    public static Bitmap getBitmap(Context context, StandardIcons icon, int size) {
        return getBitmap(context, icon, size, context.getResources().getColor(R.color.slds_color_text_icon_default));
    }

    public static Drawable getDrawable(Context context, StandardIcons icon, int size) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size));
    }

    public static Bitmap getBitmap(Context context, StandardIcons icon, int size, int color) {
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bmp);

        drawIconGlyph(context, icon.value, size, canvas, color);

        return bmp;
    }

    public static Drawable getDrawable(Context context, StandardIcons icon, int size, int color) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size, color));
    }

    public static Bitmap getBitmap(Context context, UtilityIcons icon, int size) {
        return getBitmap(context, icon, size, context.getResources().getColor(R.color.slds_color_text_icon_default));
    }

    public static Drawable getDrawable(Context context, UtilityIcons icon, int size) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size));
    }

    public static Bitmap getBitmap(Context context, UtilityIcons icon, int size, int color) {
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bmp);

        drawIconGlyph(context, icon.value, size, canvas, color);

        return bmp;
    }

    public static Drawable getDrawable(Context context, UtilityIcons icon, int size, int color) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size, color));
    }

    private static void drawIconGlyph(Context context, String iconChar, int size, Canvas canvas, int color) {
        Paint textPaint = new Paint();
        textPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
        textPaint.setTextAlign(Paint.Align.CENTER);
        textPaint.setColor(color);
        textPaint.setTextSize(size);
        textPaint.setTypeface(Typeface.createFromAsset(
                context.getResources().getAssets(), "SalesforceDesignSystemIcons.ttf"));
        float y = (size / 2.0f) - ((textPaint.descent() + textPaint.ascent()) / 2.0f);
        canvas.drawText(iconChar, (size / 2.0f), y, textPaint);
    }

    public enum ActionIcons {
        ActionAddContact ("\uEA01"),
        ActionAddFile ("\uEA02"),
        ActionAddPhotoVideo ("\uEA03"),
        ActionAddRelationship ("\uEA04"),
        ActionAnnouncement ("\uEA05"),
        ActionApex ("\uEA06"),
        ActionApproval ("\uEA07"),
        ActionBack ("\uEA08"),
        ActionCall ("\uEA09"),
        ActionCanvas ("\uEA0A"),
        ActionChangeOwner ("\uEA0B"),
        ActionChangeRecordType ("\uEA0C"),
        ActionCheck ("\uEA0D"),
        ActionClone ("\uEA0E"),
        ActionClose ("\uEA0F"),
        ActionDefer ("\uEA10"),
        ActionDelete ("\uEA11"),
        ActionDescription ("\uEA12"),
        ActionDialIn ("\uEA13"),
        ActionDownload ("\uEA14"),
        ActionEdit ("\uEA15"),
        ActionEditGroups ("\uEA16"),
        ActionEditRelationship ("\uEA17"),
        ActionEmail ("\uEA18"),
        ActionFallback ("\uEA19"),
        ActionFilter ("\uEA1A"),
        ActionFlow ("\uEA1B"),
        ActionFollow ("\uEA1C"),
        ActionFollowing ("\uEA1D"),
        ActionFreezeUser ("\uEA1E"),
        ActionGoal ("\uEA1F"),
        ActionGoogleNews ("\uEA20"),
        ActionInfo ("\uEA21"),
        ActionJoinGroup ("\uEA22"),
        ActionLeadConvert ("\uEA23"),
        ActionLeaveGroup ("\uEA24"),
        ActionLogACall ("\uEA25"),
        ActionLogEvent ("\uEA26"),
        ActionManagePermSets ("\uEA27"),
        ActionMap ("\uEA28"),
        ActionMore ("\uEA29"),
        ActionNew ("\uEA2A"),
        ActionNewAccount ("\uEA2B"),
        ActionNewCampaign ("\uEA2C"),
        ActionNewCase ("\uEA2D"),
        ActionNewChildCase ("\uEA2E"),
        ActionNewContact ("\uEA2F"),
        ActionNewCustom1 ("\uEA30"),
        ActionNewCustom10 ("\uEA31"),
        ActionNewCustom100 ("\uEA32"),
        ActionNewCustom11 ("\uEA33"),
        ActionNewCustom12 ("\uEA34"),
        ActionNewCustom13 ("\uEA35"),
        ActionNewCustom14 ("\uEA36"),
        ActionNewCustom15 ("\uEA37"),
        ActionNewCustom16 ("\uEA38"),
        ActionNewCustom17 ("\uEA39"),
        ActionNewCustom18 ("\uEA3A"),
        ActionNewCustom19 ("\uEA3B"),
        ActionNewCustom2 ("\uEA3C"),
        ActionNewCustom20 ("\uEA3D"),
        ActionNewCustom21 ("\uEA3E"),
        ActionNewCustom22 ("\uEA3F"),
        ActionNewCustom23 ("\uEA40"),
        ActionNewCustom24 ("\uEA41"),
        ActionNewCustom25 ("\uEA42"),
        ActionNewCustom26 ("\uEA43"),
        ActionNewCustom27 ("\uEA44"),
        ActionNewCustom28 ("\uEA45"),
        ActionNewCustom29 ("\uEA46"),
        ActionNewCustom3 ("\uEA47"),
        ActionNewCustom30 ("\uEA48"),
        ActionNewCustom31 ("\uEA49"),
        ActionNewCustom32 ("\uEA4A"),
        ActionNewCustom33 ("\uEA4B"),
        ActionNewCustom34 ("\uEA4C"),
        ActionNewCustom35 ("\uEA4D"),
        ActionNewCustom36 ("\uEA4E"),
        ActionNewCustom37 ("\uEA4F"),
        ActionNewCustom38 ("\uEA50"),
        ActionNewCustom39 ("\uEA51"),
        ActionNewCustom4 ("\uEA52"),
        ActionNewCustom40 ("\uEA53"),
        ActionNewCustom41 ("\uEA54"),
        ActionNewCustom42 ("\uEA55"),
        ActionNewCustom43 ("\uEA56"),
        ActionNewCustom44 ("\uEA57"),
        ActionNewCustom45 ("\uEA58"),
        ActionNewCustom46 ("\uEA59"),
        ActionNewCustom47 ("\uEA5A"),
        ActionNewCustom48 ("\uEA5B"),
        ActionNewCustom49 ("\uEA5C"),
        ActionNewCustom5 ("\uEA5D"),
        ActionNewCustom50 ("\uEA5E"),
        ActionNewCustom51 ("\uEA5F"),
        ActionNewCustom52 ("\uEA60"),
        ActionNewCustom53 ("\uEA61"),
        ActionNewCustom54 ("\uEA62"),
        ActionNewCustom55 ("\uEA63"),
        ActionNewCustom56 ("\uEA64"),
        ActionNewCustom57 ("\uEA65"),
        ActionNewCustom58 ("\uEA66"),
        ActionNewCustom59 ("\uEA67"),
        ActionNewCustom6 ("\uEA68"),
        ActionNewCustom60 ("\uEA69"),
        ActionNewCustom61 ("\uEA6A"),
        ActionNewCustom62 ("\uEA6B"),
        ActionNewCustom63 ("\uEA6C"),
        ActionNewCustom64 ("\uEA6D"),
        ActionNewCustom65 ("\uEA6E"),
        ActionNewCustom66 ("\uEA6F"),
        ActionNewCustom67 ("\uEA70"),
        ActionNewCustom68 ("\uEA71"),
        ActionNewCustom69 ("\uEA72"),
        ActionNewCustom7 ("\uEA73"),
        ActionNewCustom70 ("\uEA74"),
        ActionNewCustom71 ("\uEA75"),
        ActionNewCustom72 ("\uEA76"),
        ActionNewCustom73 ("\uEA77"),
        ActionNewCustom74 ("\uEA78"),
        ActionNewCustom75 ("\uEA79"),
        ActionNewCustom76 ("\uEA7A"),
        ActionNewCustom77 ("\uEA7B"),
        ActionNewCustom78 ("\uEA7C"),
        ActionNewCustom79 ("\uEA7D"),
        ActionNewCustom8 ("\uEA7E"),
        ActionNewCustom80 ("\uEA7F"),
        ActionNewCustom81 ("\uEA80"),
        ActionNewCustom82 ("\uEA81"),
        ActionNewCustom83 ("\uEA82"),
        ActionNewCustom84 ("\uEA83"),
        ActionNewCustom85 ("\uEA84"),
        ActionNewCustom86 ("\uEA85"),
        ActionNewCustom87 ("\uEA86"),
        ActionNewCustom88 ("\uEA87"),
        ActionNewCustom89 ("\uEA88"),
        ActionNewCustom9 ("\uEA89"),
        ActionNewCustom90 ("\uEA8A"),
        ActionNewCustom91 ("\uEA8B"),
        ActionNewCustom92 ("\uEA8C"),
        ActionNewCustom93 ("\uEA8D"),
        ActionNewCustom94 ("\uEA8E"),
        ActionNewCustom95 ("\uEA8F"),
        ActionNewCustom96 ("\uEA90"),
        ActionNewCustom97 ("\uEA91"),
        ActionNewCustom98 ("\uEA92"),
        ActionNewCustom99 ("\uEA93"),
        ActionNewEvent ("\uEA94"),
        ActionNewGroup ("\uEA95"),
        ActionNewLead ("\uEA96"),
        ActionNewNote ("\uEA97"),
        ActionNewNotebook ("\uEA98"),
        ActionNewOpportunity ("\uEA99"),
        ActionNewPersonAccount ("\uEA9A"),
        ActionNewTask ("\uEA9B"),
        ActionPasswordUnlock ("\uEA9C"),
        ActionPreview ("\uEA9D"),
        ActionPriority ("\uEA9E"),
        ActionQuestionPostAction ("\uEA9F"),
        ActionQuote ("\uEAA0"),
        ActionRecall ("\uEAA1"),
        ActionRecord ("\uEAA2"),
        ActionRefresh ("\uEAA3"),
        ActionReject ("\uEAA4"),
        ActionRemove ("\uEAA5"),
        ActionRemoveRelationship ("\uEAA6"),
        ActionResetPassword ("\uEAA7"),
        ActionShare ("\uEAA8"),
        ActionShareFile ("\uEAA9"),
        ActionShareLink ("\uEAAA"),
        ActionSharePoll ("\uEAAB"),
        ActionSharePost ("\uEAAC"),
        ActionShareThanks ("\uEAAD"),
        ActionSort ("\uEAAE"),
        ActionSubmitForApproval ("\uEAAF"),
        ActionUpdate ("\uEAB0"),
        ActionUpdateStatus ("\uEAB1"),
        ActionUpload ("\uEAB2"),
        ActionUser ("\uEAB3"),
        ActionUserActivation ("\uEAB4"),
        ActionViewRelationship ("\uEAB5"),
        ActionWebLink ("\uEAB6");

        final String value;
        ActionIcons(String value) { this.value = value; }
    }

    public enum CustomIcons {
        Custom1 ("\uEAB7"),
        Custom10 ("\uEAB8"),
        Custom100 ("\uEAB9"),
        Custom101 ("\uEABA"),
        Custom102 ("\uEABB"),
        Custom103 ("\uEABC"),
        Custom104 ("\uEABD"),
        Custom105 ("\uEABE"),
        Custom106 ("\uEABF"),
        Custom107 ("\uEAC0"),
        Custom108 ("\uEAC1"),
        Custom109 ("\uEAC2"),
        Custom11 ("\uEAC3"),
        Custom110 ("\uEAC4"),
        Custom111 ("\uEAC5"),
        Custom112 ("\uEAC6"),
        Custom113 ("\uEAC7"),
        Custom12 ("\uEAC8"),
        Custom13 ("\uEAC9"),
        Custom14 ("\uEACA"),
        Custom15 ("\uEACB"),
        Custom16 ("\uEACC"),
        Custom17 ("\uEACD"),
        Custom18 ("\uEACE"),
        Custom19 ("\uEACF"),
        Custom2 ("\uEAD0"),
        Custom20 ("\uEAD1"),
        Custom21 ("\uEAD2"),
        Custom22 ("\uEAD3"),
        Custom23 ("\uEAD4"),
        Custom24 ("\uEAD5"),
        Custom25 ("\uEAD6"),
        Custom26 ("\uEAD7"),
        Custom27 ("\uEAD8"),
        Custom28 ("\uEAD9"),
        Custom29 ("\uEADA"),
        Custom3 ("\uEADB"),
        Custom30 ("\uEADC"),
        Custom31 ("\uEADD"),
        Custom32 ("\uEADE"),
        Custom33 ("\uEADF"),
        Custom34 ("\uEAE0"),
        Custom35 ("\uEAE1"),
        Custom36 ("\uEAE2"),
        Custom37 ("\uEAE3"),
        Custom38 ("\uEAE4"),
        Custom39 ("\uEAE5"),
        Custom4 ("\uEAE6"),
        Custom40 ("\uEAE7"),
        Custom41 ("\uEAE8"),
        Custom42 ("\uEAE9"),
        Custom43 ("\uEAEA"),
        Custom44 ("\uEAEB"),
        Custom45 ("\uEAEC"),
        Custom46 ("\uEAED"),
        Custom47 ("\uEAEE"),
        Custom48 ("\uEAEF"),
        Custom49 ("\uEAF0"),
        Custom5 ("\uEAF1"),
        Custom50 ("\uEAF2"),
        Custom51 ("\uEAF3"),
        Custom52 ("\uEAF4"),
        Custom53 ("\uEAF5"),
        Custom54 ("\uEAF6"),
        Custom55 ("\uEAF7"),
        Custom56 ("\uEAF8"),
        Custom57 ("\uEAF9"),
        Custom58 ("\uEAFA"),
        Custom59 ("\uEAFB"),
        Custom6 ("\uEAFC"),
        Custom60 ("\uEAFD"),
        Custom61 ("\uEAFE"),
        Custom62 ("\uEAFF"),
        Custom63 ("\uEB00"),
        Custom64 ("\uEB01"),
        Custom65 ("\uEB02"),
        Custom66 ("\uEB03"),
        Custom67 ("\uEB04"),
        Custom68 ("\uEB05"),
        Custom69 ("\uEB06"),
        Custom7 ("\uEB07"),
        Custom70 ("\uEB08"),
        Custom71 ("\uEB09"),
        Custom72 ("\uEB0A"),
        Custom73 ("\uEB0B"),
        Custom74 ("\uEB0C"),
        Custom75 ("\uEB0D"),
        Custom76 ("\uEB0E"),
        Custom77 ("\uEB0F"),
        Custom78 ("\uEB10"),
        Custom79 ("\uEB11"),
        Custom8 ("\uEB12"),
        Custom80 ("\uEB13"),
        Custom81 ("\uEB14"),
        Custom82 ("\uEB15"),
        Custom83 ("\uEB16"),
        Custom84 ("\uEB17"),
        Custom85 ("\uEB18"),
        Custom86 ("\uEB19"),
        Custom87 ("\uEB1A"),
        Custom88 ("\uEB1B"),
        Custom89 ("\uEB1C"),
        Custom9 ("\uEB1D"),
        Custom90 ("\uEB1E"),
        Custom91 ("\uEB1F"),
        Custom92 ("\uEB20"),
        Custom93 ("\uEB21"),
        Custom94 ("\uEB22"),
        Custom95 ("\uEB23"),
        Custom96 ("\uEB24"),
        Custom97 ("\uEB25"),
        Custom98 ("\uEB26"),
        Custom99 ("\uEB27");

        final String value;
        CustomIcons(String value) { this.value = value; }
    }

    public enum StandardIcons {
        StandardAccount ("\uEB28"),
        StandardAddress ("\uEB29"),
        StandardAnnouncement ("\uEB2A"),
        StandardAnswerBest ("\uEB2B"),
        StandardAnswerPrivate ("\uEB2C"),
        StandardAnswerPublic ("\uEB2D"),
        StandardApproval ("\uEB2E"),
        StandardApps ("\uEB2F"),
        StandardAppsAdmin ("\uEB30"),
        StandardArticle ("\uEB31"),
        StandardAssetRelationship ("\uEB32"),
        StandardAssignedResource ("\uEB33"),
        StandardAvatar ("\uEB34"),
        StandardAvatarLoading ("\uEB35"),
        StandardBot ("\uEB36"),
        StandardBusinessHours ("\uEB37"),
        StandardCalibration ("\uEB38"),
        StandardCall ("\uEB39"),
        StandardCallHistory ("\uEB3A"),
        StandardCampaign ("\uEB3B"),
        StandardCampaignMembers ("\uEB3C"),
        StandardCanvas ("\uEB3D"),
        StandardCarousel ("\uEB3E"),
        StandardCase ("\uEB3F"),
        StandardCaseChangeStatus ("\uEB40"),
        StandardCaseComment ("\uEB41"),
        StandardCaseEmail ("\uEB42"),
        StandardCaseLogACall ("\uEB43"),
        StandardCaseMilestone ("\uEB44"),
        StandardCaseTranscript ("\uEB45"),
        StandardClient ("\uEB46"),
        StandardCms ("\uEB47"),
        StandardCoaching ("\uEB48"),
        StandardConnectedApps ("\uEB49"),
        StandardContact ("\uEB4A"),
        StandardContactList ("\uEB4B"),
        StandardContract ("\uEB4C"),
        StandardContractLineItem ("\uEB4D"),
        StandardCustom ("\uEB4E"),
        StandardCustomNotification ("\uEB4F"),
        StandardDashboard ("\uEB50"),
        StandardDatadotcom ("\uEB51"),
        StandardDefault ("\uEB52"),
        StandardDocument ("\uEB53"),
        StandardDrafts ("\uEB54"),
        StandardEmail ("\uEB55"),
        StandardEmailChatter ("\uEB56"),
        StandardEmpty ("\uEB57"),
        StandardEndorsement ("\uEB58"),
        StandardEntitlement ("\uEB59"),
        StandardEntitlementProcess ("\uEB5A"),
        StandardEntitlementTemplate ("\uEB5B"),
        StandardEntity ("\uEB5C"),
        StandardEntityMilestone ("\uEB5D"),
        StandardEnvironmentHub ("\uEB5E"),
        StandardEvent ("\uEB5F"),
        StandardFeed ("\uEB60"),
        StandardFeedback ("\uEB61"),
        StandardFile ("\uEB62"),
        StandardFlow ("\uEB63"),
        StandardFolder ("\uEB64"),
        StandardForecasts ("\uEB65"),
        StandardGenericLoading ("\uEB66"),
        StandardGoals ("\uEB67"),
        StandardGroupLoading ("\uEB68"),
        StandardGroups ("\uEB69"),
        StandardHierarchy ("\uEB6A"),
        StandardHome ("\uEB6B"),
        StandardHousehold ("\uEB6C"),
        StandardInsights ("\uEB6D"),
        StandardInvestmentAccount ("\uEB6E"),
        StandardLead ("\uEB6F"),
        StandardLeadInsights ("\uEB70"),
        StandardLeadList ("\uEB71"),
        StandardLink ("\uEB72"),
        StandardListEmail ("\uEB73"),
        StandardLiveChat ("\uEB74"),
        StandardLocation ("\uEB75"),
        StandardLogACall ("\uEB76"),
        StandardMacros ("\uEB77"),
        StandardMaintenanceAsset ("\uEB78"),
        StandardMaintenancePlan ("\uEB79"),
        StandardMarketingActions ("\uEB7A"),
        StandardMerge ("\uEB7B"),
        StandardMetrics ("\uEB7C"),
        StandardNews ("\uEB7D"),
        StandardNote ("\uEB7E"),
        StandardOmniSupervisor ("\uEB7F"),
        StandardOperatingHours ("\uEB80"),
        StandardOpportunity ("\uEB81"),
        StandardOpportunitySplits ("\uEB82"),
        StandardOrders ("\uEB83"),
        StandardPeople ("\uEB84"),
        StandardPerformance ("\uEB85"),
        StandardPersonAccount ("\uEB86"),
        StandardPhoto ("\uEB87"),
        StandardPoll ("\uEB88"),
        StandardPortal ("\uEB89"),
        StandardPost ("\uEB8A"),
        StandardPricebook ("\uEB8B"),
        StandardProcess ("\uEB8C"),
        StandardProduct ("\uEB8D"),
        StandardProductConsumed ("\uEB8E"),
        StandardProductItem ("\uEB8F"),
        StandardProductItemTransaction ("\uEB90"),
        StandardProductRequest ("\uEB91"),
        StandardProductRequestLineItem ("\uEB92"),
        StandardProductRequired ("\uEB93"),
        StandardProductTransfer ("\uEB94"),
        StandardQuestionBest ("\uEB95"),
        StandardQuestionFeed ("\uEB96"),
        StandardQuickText ("\uEB97"),
        StandardQuip ("\uEB98"),
        StandardQuipSheet ("\uEB99"),
        StandardQuotes ("\uEB9A"),
        StandardRecent ("\uEB9B"),
        StandardRecord ("\uEB9C"),
        StandardRelatedList ("\uEB9D"),
        StandardRelationship ("\uEB9E"),
        StandardReport ("\uEB9F"),
        StandardResourceAbsence ("\uEBA0"),
        StandardResourceCapacity ("\uEBA1"),
        StandardResourcePreference ("\uEBA2"),
        StandardResourceSkill ("\uEBA3"),
        StandardReward ("\uEBA4"),
        StandardRtcPresence ("\uEBA5"),
        StandardSalesPath ("\uEBA6"),
        StandardScanCard ("\uEBA7"),
        StandardServiceAppointment ("\uEBA8"),
        StandardServiceContract ("\uEBA9"),
        StandardServiceCrew ("\uEBAA"),
        StandardServiceCrewMember ("\uEBAB"),
        StandardServiceReport ("\uEBAC"),
        StandardServiceResource ("\uEBAD"),
        StandardServiceTerritory ("\uEBAE"),
        StandardServiceTerritoryLocation ("\uEBAF"),
        StandardServiceTerritoryMember ("\uEBB0"),
        StandardShipment ("\uEBB1"),
        StandardSkill ("\uEBB2"),
        StandardSkillEntity ("\uEBB3"),
        StandardSkillRequirement ("\uEBB4"),
        StandardSocial ("\uEBB5"),
        StandardSolution ("\uEBB6"),
        StandardSossession ("\uEBB7"),
        StandardTask ("\uEBB8"),
        StandardTask2 ("\uEBB9"),
        StandardTeamMember ("\uEBBA"),
        StandardTemplate ("\uEBBB"),
        StandardThanks ("\uEBBC"),
        StandardThanksLoading ("\uEBBD"),
        StandardTimesheet ("\uEBBE"),
        StandardTimesheetEntry ("\uEBBF"),
        StandardTimeslot ("\uEBC0"),
        StandardToday ("\uEBC1"),
        StandardTopic ("\uEBC2"),
        StandardTopic2 ("\uEBC3"),
        StandardUnmatched ("\uEBC4"),
        StandardUser ("\uEBC5"),
        StandardWorkOrder ("\uEBC6"),
        StandardWorkOrderItem ("\uEBC7"),
        StandardWorkType ("\uEBC8");

        final String value;
        StandardIcons(String value) { this.value = value; }
    }

    public enum UtilityIcons {
        UtilityActivity ("\uEBC9"),
        UtilityAdSet ("\uEBCA"),
        UtilityAdd ("\uEBCB"),
        UtilityAdduser ("\uEBCC"),
        UtilityAnchor ("\uEBCD"),
        UtilityAnimalAndNature ("\uEBCE"),
        UtilityAnnouncement ("\uEBCF"),
        UtilityAnswer ("\uEBD0"),
        UtilityAnsweredTwice ("\uEBD1"),
        UtilityApex ("\uEBD2"),
        UtilityApproval ("\uEBD3"),
        UtilityApps ("\uEBD4"),
        UtilityArrowdown ("\uEBD5"),
        UtilityArrowup ("\uEBD6"),
        UtilityAttach ("\uEBD7"),
        UtilityAutomate ("\uEBD8"),
        UtilityBack ("\uEBD9"),
        UtilityBan ("\uEBDA"),
        UtilityBlockVisitor ("\uEBDB"),
        UtilityBold ("\uEBDC"),
        UtilityBookmark ("\uEBDD"),
        UtilityBreadcrumbs ("\uEBDE"),
        UtilityBroadcast ("\uEBDF"),
        UtilityBrush ("\uEBE0"),
        UtilityBucket ("\uEBE1"),
        UtilityBuilder ("\uEBE2"),
        UtilityCall ("\uEBE3"),
        UtilityCampaign ("\uEBE4"),
        UtilityCancelFileRequest ("\uEBE5"),
        UtilityCancelTransfer ("\uEBE6"),
        UtilityCapslock ("\uEBE7"),
        UtilityCase ("\uEBE8"),
        UtilityCases ("\uEBE9"),
        UtilityCenterAlignText ("\uEBEA"),
        UtilityChangeOwner ("\uEBEB"),
        UtilityChangeRecordType ("\uEBEC"),
        UtilityChart ("\uEBED"),
        UtilityChat ("\uEBEE"),
        UtilityCheck ("\uEBEF"),
        UtilityCheckin ("\uEBF0"),
        UtilityChevrondown ("\uEBF1"),
        UtilityChevronleft ("\uEBF2"),
        UtilityChevronright ("\uEBF3"),
        UtilityChevronup ("\uEBF4"),
        UtilityClassicInterface ("\uEBF5"),
        UtilityClear ("\uEBF6"),
        UtilityClock ("\uEBF7"),
        UtilityClose ("\uEBF8"),
        UtilityCollapseAll ("\uEBF9"),
        UtilityComments ("\uEBFA"),
        UtilityCompany ("\uEBFB"),
        UtilityConnectedApps ("\uEBFC"),
        UtilityContract ("\uEBFD"),
        UtilityContractAlt ("\uEBFE"),
        UtilityCopy ("\uEBFF"),
        UtilityCopyToClipboard ("\uEC00"),
        UtilityCrossfilter ("\uEC01"),
        UtilityCustomApps ("\uEC02"),
        UtilityCut ("\uEC03"),
        UtilityDash ("\uEC04"),
        UtilityDatabase ("\uEC05"),
        UtilityDatadotcom ("\uEC06"),
        UtilityDayview ("\uEC07"),
        UtilityDelete ("\uEC08"),
        UtilityDeprecate ("\uEC09"),
        UtilityDescription ("\uEC0A"),
        UtilityDesktop ("\uEC0B"),
        UtilityDislike ("\uEC0C"),
        UtilityDockPanel ("\uEC0D"),
        UtilityDown ("\uEC0E"),
        UtilityDownload ("\uEC0F"),
        UtilityEdit ("\uEC10"),
        UtilityEditForm ("\uEC11"),
        UtilityEmail ("\uEC12"),
        UtilityEmoji ("\uEC13"),
        UtilityEndCall ("\uEC14"),
        UtilityEndChat ("\uEC15"),
        UtilityErectWindow ("\uEC16"),
        UtilityError ("\uEC17"),
        UtilityEvent ("\uEC18"),
        UtilityExpand ("\uEC19"),
        UtilityExpandAll ("\uEC1A"),
        UtilityExpandAlt ("\uEC1B"),
        UtilityFallback ("\uEC1C"),
        UtilityFavorite ("\uEC1D"),
        UtilityFeed ("\uEC1E"),
        UtilityFile ("\uEC1F"),
        UtilityFilter ("\uEC20"),
        UtilityFilterList ("\uEC21"),
        UtilityFlow ("\uEC22"),
        UtilityFoodAndDrink ("\uEC23"),
        UtilityForward ("\uEC24"),
        UtilityFrozen ("\uEC25"),
        UtilityFullWidthView ("\uEC26"),
        UtilityGraph ("\uEC27"),
        UtilityGroups ("\uEC28"),
        UtilityHelp ("\uEC29"),
        UtilityHide ("\uEC2A"),
        UtilityHome ("\uEC2B"),
        UtilityIdentity ("\uEC2C"),
        UtilityImage ("\uEC2D"),
        UtilityInbox ("\uEC2E"),
        UtilityInfo ("\uEC2F"),
        UtilityInfoAlt ("\uEC30"),
        UtilityInsertTagField ("\uEC31"),
        UtilityInsertTemplate ("\uEC32"),
        UtilityInternalShare ("\uEC33"),
        UtilityItalic ("\uEC34"),
        UtilityJumpToBottom ("\uEC35"),
        UtilityJumpToTop ("\uEC36"),
        UtilityJustifyText ("\uEC37"),
        UtilityKanban ("\uEC38"),
        UtilityKeyboardDismiss ("\uEC39"),
        UtilityKnowledgeBase ("\uEC3A"),
        UtilityLayers ("\uEC3B"),
        UtilityLayout ("\uEC3C"),
        UtilityLeft ("\uEC3D"),
        UtilityLeftAlignText ("\uEC3E"),
        UtilityLevelUp ("\uEC3F"),
        UtilityLightBulb ("\uEC40"),
        UtilityLike ("\uEC41"),
        UtilityLink ("\uEC42"),
        UtilityList ("\uEC43"),
        UtilityLocation ("\uEC44"),
        UtilityLock ("\uEC45"),
        UtilityLogACall ("\uEC46"),
        UtilityLogout ("\uEC47"),
        UtilityLowerFlag ("\uEC48"),
        UtilityMacros ("\uEC49"),
        UtilityMagicwand ("\uEC4A"),
        UtilityMarkAllAsRead ("\uEC4B"),
        UtilityMatrix ("\uEC4C"),
        UtilityMerge ("\uEC4D"),
        UtilityMergeField ("\uEC4E"),
        UtilityMetrics ("\uEC4F"),
        UtilityMinimizeWindow ("\uEC50"),
        UtilityMoneybag ("\uEC51"),
        UtilityMonthlyview ("\uEC52"),
        UtilityMove ("\uEC53"),
        UtilityMuted ("\uEC54"),
        UtilityNew ("\uEC55"),
        UtilityNewDirectMessage ("\uEC56"),
        UtilityNewWindow ("\uEC57"),
        UtilityNews ("\uEC58"),
        UtilityNote ("\uEC59"),
        UtilityNotebook ("\uEC5A"),
        UtilityNotification ("\uEC5B"),
        UtilityOffice365 ("\uEC5C"),
        UtilityOffline ("\uEC5D"),
        UtilityOfflineCached ("\uEC5E"),
        UtilityOmniChannel ("\uEC5F"),
        UtilityOpen ("\uEC60"),
        UtilityOpenFolder ("\uEC61"),
        UtilityOpenedFolder ("\uEC62"),
        UtilityOverflow ("\uEC63"),
        UtilityPackage ("\uEC64"),
        UtilityPackageOrg ("\uEC65"),
        UtilityPackageOrgBeta ("\uEC66"),
        UtilityPage ("\uEC67"),
        UtilityPalette ("\uEC68"),
        UtilityPaste ("\uEC69"),
        UtilityPause ("\uEC6A"),
        UtilityPeople ("\uEC6B"),
        UtilityPhoneLandscape ("\uEC6C"),
        UtilityPhonePortrait ("\uEC6D"),
        UtilityPhoto ("\uEC6E"),
        UtilityPicklist ("\uEC6F"),
        UtilityPin ("\uEC70"),
        UtilityPinned ("\uEC71"),
        UtilityPower ("\uEC72"),
        UtilityPreview ("\uEC73"),
        UtilityPriority ("\uEC74"),
        UtilityPrivatelyShared ("\uEC75"),
        UtilityProcess ("\uEC76"),
        UtilityPush ("\uEC77"),
        UtilityPuzzle ("\uEC78"),
        UtilityQuestion ("\uEC79"),
        UtilityQuestionMark ("\uEC7A"),
        UtilityQuestionsAndAnswers ("\uEC7B"),
        UtilityQuickText ("\uEC7C"),
        UtilityQuotationMarks ("\uEC7D"),
        UtilityRating ("\uEC7E"),
        UtilityRecord ("\uEC7F"),
        UtilityRecordCreate ("\uEC80"),
        UtilityRedo ("\uEC81"),
        UtilityRefresh ("\uEC82"),
        UtilityRelate ("\uEC83"),
        UtilityReminder ("\uEC84"),
        UtilityRemoveFormatting ("\uEC85"),
        UtilityRemoveLink ("\uEC86"),
        UtilityReplace ("\uEC87"),
        UtilityReply ("\uEC88"),
        UtilityReplyAll ("\uEC89"),
        UtilityResetPassword ("\uEC8A"),
        UtilityResourceAbsence ("\uEC8B"),
        UtilityResourceCapacity ("\uEC8C"),
        UtilityResourceTerritory ("\uEC8D"),
        UtilityRetweet ("\uEC8E"),
        UtilityRichtextbulletedlist ("\uEC8F"),
        UtilityRichtextindent ("\uEC90"),
        UtilityRichtextnumberedlist ("\uEC91"),
        UtilityRichtextoutdent ("\uEC92"),
        UtilityRight ("\uEC93"),
        UtilityRightAlignText ("\uEC94"),
        UtilityRotate ("\uEC95"),
        UtilityRows ("\uEC96"),
        UtilityRules ("\uEC97"),
        UtilitySalesforce1 ("\uEC98"),
        UtilitySave ("\uEC99"),
        UtilitySearch ("\uEC9A"),
        UtilitySettings ("\uEC9B"),
        UtilitySetup ("\uEC9C"),
        UtilitySetupAssistantGuide ("\uEC9D"),
        UtilityShare ("\uEC9E"),
        UtilityShareFile ("\uEC9F"),
        UtilityShareMobile ("\uECA0"),
        UtilitySharePost ("\uECA1"),
        UtilityShield ("\uECA2"),
        UtilityShoppingBag ("\uECA3"),
        UtilitySideList ("\uECA4"),
        UtilitySignpost ("\uECA5"),
        UtilitySmileyAndPeople ("\uECA6"),
        UtilitySms ("\uECA7"),
        UtilitySnippet ("\uECA8"),
        UtilitySocialshare ("\uECA9"),
        UtilitySort ("\uECAA"),
        UtilitySpinner ("\uECAB"),
        UtilityStandardObjects ("\uECAC"),
        UtilityStop ("\uECAD"),
        UtilityStrikethrough ("\uECAE"),
        UtilitySuccess ("\uECAF"),
        UtilitySummary ("\uECB0"),
        UtilitySummarydetail ("\uECB1"),
        UtilitySwitch ("\uECB2"),
        UtilitySymbols ("\uECB3"),
        UtilitySync ("\uECB4"),
        UtilityTable ("\uECB5"),
        UtilityTabletLandscape ("\uECB6"),
        UtilityTabletPortrait ("\uECB7"),
        UtilityTabset ("\uECB8"),
        UtilityTask ("\uECB9"),
        UtilityTextBackgroundColor ("\uECBA"),
        UtilityTextColor ("\uECBB"),
        UtilityThreedots ("\uECBC"),
        UtilityThreedotsVertical ("\uECBD"),
        UtilityThunder ("\uECBE"),
        UtilityTileCardList ("\uECBF"),
        UtilityTopic ("\uECC0"),
        UtilityTouchAction ("\uECC1"),
        UtilityTrail ("\uECC2"),
        UtilityTravelAndPlaces ("\uECC3"),
        UtilityTrending ("\uECC4"),
        UtilityTurnOffNotifications ("\uECC5"),
        UtilityTypeTool ("\uECC6"),
        UtilityUndelete ("\uECC7"),
        UtilityUndeprecate ("\uECC8"),
        UtilityUnderline ("\uECC9"),
        UtilityUndo ("\uECCA"),
        UtilityUnlock ("\uECCB"),
        UtilityUnmuted ("\uECCC"),
        UtilityUp ("\uECCD"),
        UtilityUpload ("\uECCE"),
        UtilityUser ("\uECCF"),
        UtilityUserRole ("\uECD0"),
        UtilityVideo ("\uECD1"),
        UtilityVoicemailDrop ("\uECD2"),
        UtilityVolumeHigh ("\uECD3"),
        UtilityVolumeLow ("\uECD4"),
        UtilityVolumeOff ("\uECD5"),
        UtilityWarning ("\uECD6"),
        UtilityWeeklyview ("\uECD7"),
        UtilityWifi ("\uECD8"),
        UtilityWorkOrderType ("\uECD9"),
        UtilityWorld ("\uECDA"),
        UtilityYubiKey ("\uECDB"),
        UtilityZoomin ("\uECDC"),
        UtilityZoomout ("\uECDD");

        final String value;
        UtilityIcons(String value) { this.value = value; }
    }


}
