/// Copyright (c) 2015-present, salesforce.com, inc. All rights reserved
/// Licensed under BSD 3-Clause - see LICENSE.txt or git.io/sfdc-license

package com.salesforce.designsystem;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.Drawable;

/**
 * Utility for generating Bitmaps from SLDS icons.
 */

public abstract class Icons {

    public static Bitmap getBitmap(Context context, ActionIcons icon, int size) {
        return getBitmap(context, icon, size, context.getResources().getColor(R.color.slds_color_text_icon_default));
    }

    public static Drawable getDrawable(Context context, ActionIcons icon, int size) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size));
    }

    public static Bitmap getBitmap(Context context, ActionIcons icon, int size, int color) {
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bmp);

        drawIconGlyph(context, icon.value, size, canvas, color);

        return bmp;
    }

    public static Drawable getDrawable(Context context, ActionIcons icon, int size, int color) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size, color));
    }

    public static Bitmap getBitmap(Context context, CustomIcons icon, int size) {
        return getBitmap(context, icon, size, context.getResources().getColor(R.color.slds_color_text_icon_default));
    }

    public static Drawable getDrawable(Context context, CustomIcons icon, int size) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size));
    }

    public static Bitmap getBitmap(Context context, CustomIcons icon, int size, int color) {
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bmp);

        drawIconGlyph(context, icon.value, size, canvas, color);

        return bmp;
    }

    public static Drawable getDrawable(Context context, CustomIcons icon, int size, int color) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size, color));
    }

    public static Bitmap getBitmap(Context context, StandardIcons icon, int size) {
        return getBitmap(context, icon, size, context.getResources().getColor(R.color.slds_color_text_icon_default));
    }

    public static Drawable getDrawable(Context context, StandardIcons icon, int size) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size));
    }

    public static Bitmap getBitmap(Context context, StandardIcons icon, int size, int color) {
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bmp);

        drawIconGlyph(context, icon.value, size, canvas, color);

        return bmp;
    }

    public static Drawable getDrawable(Context context, StandardIcons icon, int size, int color) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size, color));
    }

    public static Bitmap getBitmap(Context context, UtilityIcons icon, int size) {
        return getBitmap(context, icon, size, context.getResources().getColor(R.color.slds_color_text_icon_default));
    }

    public static Drawable getDrawable(Context context, UtilityIcons icon, int size) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size));
    }

    public static Bitmap getBitmap(Context context, UtilityIcons icon, int size, int color) {
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bmp);

        drawIconGlyph(context, icon.value, size, canvas, color);

        return bmp;
    }

    public static Drawable getDrawable(Context context, UtilityIcons icon, int size, int color) {
        return new BitmapDrawable(context.getResources(), getBitmap(context, icon, size, color));
    }

    private static void drawIconGlyph(Context context, String iconChar, int size, Canvas canvas, int color) {
        Paint textPaint = new Paint();
        textPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
        textPaint.setTextAlign(Paint.Align.CENTER);
        textPaint.setColor(color);
        textPaint.setTextSize(size);
        textPaint.setTypeface(Typeface.createFromAsset(
                context.getResources().getAssets(), "SalesforceDesignSystemIcons.ttf"));
        float y = (size / 2.0f) - ((textPaint.descent() + textPaint.ascent()) / 2.0f);
        canvas.drawText(iconChar, (size / 2.0f), y, textPaint);
    }

    public enum ActionIcons {
        ActionAddContact ("\uEA01"),
        ActionAddFile ("\uEA02"),
        ActionAddPhotoVideo ("\uEA03"),
        ActionAddRelationship ("\uEA04"),
        ActionAnnouncement ("\uEA05"),
        ActionApex ("\uEA06"),
        ActionApproval ("\uEA07"),
        ActionBack ("\uEA08"),
        ActionCall ("\uEA09"),
        ActionCanvas ("\uEA0A"),
        ActionChangeOwner ("\uEA0B"),
        ActionChangeRecordType ("\uEA0C"),
        ActionCheck ("\uEA0D"),
        ActionClone ("\uEA0E"),
        ActionClose ("\uEA0F"),
        ActionDefer ("\uEA10"),
        ActionDelete ("\uEA11"),
        ActionDescription ("\uEA12"),
        ActionDialIn ("\uEA13"),
        ActionDownload ("\uEA14"),
        ActionEdit ("\uEA15"),
        ActionEditGroups ("\uEA16"),
        ActionEditRelationship ("\uEA17"),
        ActionEmail ("\uEA18"),
        ActionFallback ("\uEA19"),
        ActionFilter ("\uEA1A"),
        ActionFlow ("\uEA1B"),
        ActionFollow ("\uEA1C"),
        ActionFollowing ("\uEA1D"),
        ActionFreezeUser ("\uEA1E"),
        ActionGoal ("\uEA1F"),
        ActionGoogleNews ("\uEA20"),
        ActionInfo ("\uEA21"),
        ActionJoinGroup ("\uEA22"),
        ActionLeadConvert ("\uEA23"),
        ActionLeaveGroup ("\uEA24"),
        ActionLogACall ("\uEA25"),
        ActionLogEvent ("\uEA26"),
        ActionManagePermSets ("\uEA27"),
        ActionMap ("\uEA28"),
        ActionMore ("\uEA29"),
        ActionNew ("\uEA2A"),
        ActionNewAccount ("\uEA2B"),
        ActionNewCampaign ("\uEA2C"),
        ActionNewCase ("\uEA2D"),
        ActionNewChildCase ("\uEA2E"),
        ActionNewContact ("\uEA2F"),
        ActionNewCustom1 ("\uEA30"),
        ActionNewCustom10 ("\uEA31"),
        ActionNewCustom100 ("\uEA32"),
        ActionNewCustom11 ("\uEA33"),
        ActionNewCustom12 ("\uEA34"),
        ActionNewCustom13 ("\uEA35"),
        ActionNewCustom14 ("\uEA36"),
        ActionNewCustom15 ("\uEA37"),
        ActionNewCustom16 ("\uEA38"),
        ActionNewCustom17 ("\uEA39"),
        ActionNewCustom18 ("\uEA3A"),
        ActionNewCustom19 ("\uEA3B"),
        ActionNewCustom2 ("\uEA3C"),
        ActionNewCustom20 ("\uEA3D"),
        ActionNewCustom21 ("\uEA3E"),
        ActionNewCustom22 ("\uEA3F"),
        ActionNewCustom23 ("\uEA40"),
        ActionNewCustom24 ("\uEA41"),
        ActionNewCustom25 ("\uEA42"),
        ActionNewCustom26 ("\uEA43"),
        ActionNewCustom27 ("\uEA44"),
        ActionNewCustom28 ("\uEA45"),
        ActionNewCustom29 ("\uEA46"),
        ActionNewCustom3 ("\uEA47"),
        ActionNewCustom30 ("\uEA48"),
        ActionNewCustom31 ("\uEA49"),
        ActionNewCustom32 ("\uEA4A"),
        ActionNewCustom33 ("\uEA4B"),
        ActionNewCustom34 ("\uEA4C"),
        ActionNewCustom35 ("\uEA4D"),
        ActionNewCustom36 ("\uEA4E"),
        ActionNewCustom37 ("\uEA4F"),
        ActionNewCustom38 ("\uEA50"),
        ActionNewCustom39 ("\uEA51"),
        ActionNewCustom4 ("\uEA52"),
        ActionNewCustom40 ("\uEA53"),
        ActionNewCustom41 ("\uEA54"),
        ActionNewCustom42 ("\uEA55"),
        ActionNewCustom43 ("\uEA56"),
        ActionNewCustom44 ("\uEA57"),
        ActionNewCustom45 ("\uEA58"),
        ActionNewCustom46 ("\uEA59"),
        ActionNewCustom47 ("\uEA5A"),
        ActionNewCustom48 ("\uEA5B"),
        ActionNewCustom49 ("\uEA5C"),
        ActionNewCustom5 ("\uEA5D"),
        ActionNewCustom50 ("\uEA5E"),
        ActionNewCustom51 ("\uEA5F"),
        ActionNewCustom52 ("\uEA60"),
        ActionNewCustom53 ("\uEA61"),
        ActionNewCustom54 ("\uEA62"),
        ActionNewCustom55 ("\uEA63"),
        ActionNewCustom56 ("\uEA64"),
        ActionNewCustom57 ("\uEA65"),
        ActionNewCustom58 ("\uEA66"),
        ActionNewCustom59 ("\uEA67"),
        ActionNewCustom6 ("\uEA68"),
        ActionNewCustom60 ("\uEA69"),
        ActionNewCustom61 ("\uEA6A"),
        ActionNewCustom62 ("\uEA6B"),
        ActionNewCustom63 ("\uEA6C"),
        ActionNewCustom64 ("\uEA6D"),
        ActionNewCustom65 ("\uEA6E"),
        ActionNewCustom66 ("\uEA6F"),
        ActionNewCustom67 ("\uEA70"),
        ActionNewCustom68 ("\uEA71"),
        ActionNewCustom69 ("\uEA72"),
        ActionNewCustom7 ("\uEA73"),
        ActionNewCustom70 ("\uEA74"),
        ActionNewCustom71 ("\uEA75"),
        ActionNewCustom72 ("\uEA76"),
        ActionNewCustom73 ("\uEA77"),
        ActionNewCustom74 ("\uEA78"),
        ActionNewCustom75 ("\uEA79"),
        ActionNewCustom76 ("\uEA7A"),
        ActionNewCustom77 ("\uEA7B"),
        ActionNewCustom78 ("\uEA7C"),
        ActionNewCustom79 ("\uEA7D"),
        ActionNewCustom8 ("\uEA7E"),
        ActionNewCustom80 ("\uEA7F"),
        ActionNewCustom81 ("\uEA80"),
        ActionNewCustom82 ("\uEA81"),
        ActionNewCustom83 ("\uEA82"),
        ActionNewCustom84 ("\uEA83"),
        ActionNewCustom85 ("\uEA84"),
        ActionNewCustom86 ("\uEA85"),
        ActionNewCustom87 ("\uEA86"),
        ActionNewCustom88 ("\uEA87"),
        ActionNewCustom89 ("\uEA88"),
        ActionNewCustom9 ("\uEA89"),
        ActionNewCustom90 ("\uEA8A"),
        ActionNewCustom91 ("\uEA8B"),
        ActionNewCustom92 ("\uEA8C"),
        ActionNewCustom93 ("\uEA8D"),
        ActionNewCustom94 ("\uEA8E"),
        ActionNewCustom95 ("\uEA8F"),
        ActionNewCustom96 ("\uEA90"),
        ActionNewCustom97 ("\uEA91"),
        ActionNewCustom98 ("\uEA92"),
        ActionNewCustom99 ("\uEA93"),
        ActionNewEvent ("\uEA94"),
        ActionNewGroup ("\uEA95"),
        ActionNewLead ("\uEA96"),
        ActionNewNote ("\uEA97"),
        ActionNewNotebook ("\uEA98"),
        ActionNewOpportunity ("\uEA99"),
        ActionNewPersonAccount ("\uEA9A"),
        ActionNewTask ("\uEA9B"),
        ActionPasswordUnlock ("\uEA9C"),
        ActionPreview ("\uEA9D"),
        ActionPriority ("\uEA9E"),
        ActionQuestionPostAction ("\uEA9F"),
        ActionQuote ("\uEAA0"),
        ActionRecall ("\uEAA1"),
        ActionRecord ("\uEAA2"),
        ActionRefresh ("\uEAA3"),
        ActionReject ("\uEAA4"),
        ActionRemove ("\uEAA5"),
        ActionRemoveRelationship ("\uEAA6"),
        ActionResetPassword ("\uEAA7"),
        ActionScript ("\uEAA8"),
        ActionShare ("\uEAA9"),
        ActionShareFile ("\uEAAA"),
        ActionShareLink ("\uEAAB"),
        ActionSharePoll ("\uEAAC"),
        ActionSharePost ("\uEAAD"),
        ActionShareThanks ("\uEAAE"),
        ActionSort ("\uEAAF"),
        ActionSubmitForApproval ("\uEAB0"),
        ActionUpdate ("\uEAB1"),
        ActionUpdateStatus ("\uEAB2"),
        ActionUpload ("\uEAB3"),
        ActionUser ("\uEAB4"),
        ActionUserActivation ("\uEAB5"),
        ActionViewRelationship ("\uEAB6"),
        ActionWebLink ("\uEAB7");

        final String value;
        ActionIcons(String value) { this.value = value; }
    }

    public enum CustomIcons {
        Custom1 ("\uEAB8"),
        Custom10 ("\uEAB9"),
        Custom100 ("\uEABA"),
        Custom101 ("\uEABB"),
        Custom102 ("\uEABC"),
        Custom103 ("\uEABD"),
        Custom104 ("\uEABE"),
        Custom105 ("\uEABF"),
        Custom106 ("\uEAC0"),
        Custom107 ("\uEAC1"),
        Custom108 ("\uEAC2"),
        Custom109 ("\uEAC3"),
        Custom11 ("\uEAC4"),
        Custom110 ("\uEAC5"),
        Custom111 ("\uEAC6"),
        Custom112 ("\uEAC7"),
        Custom113 ("\uEAC8"),
        Custom12 ("\uEAC9"),
        Custom13 ("\uEACA"),
        Custom14 ("\uEACB"),
        Custom15 ("\uEACC"),
        Custom16 ("\uEACD"),
        Custom17 ("\uEACE"),
        Custom18 ("\uEACF"),
        Custom19 ("\uEAD0"),
        Custom2 ("\uEAD1"),
        Custom20 ("\uEAD2"),
        Custom21 ("\uEAD3"),
        Custom22 ("\uEAD4"),
        Custom23 ("\uEAD5"),
        Custom24 ("\uEAD6"),
        Custom25 ("\uEAD7"),
        Custom26 ("\uEAD8"),
        Custom27 ("\uEAD9"),
        Custom28 ("\uEADA"),
        Custom29 ("\uEADB"),
        Custom3 ("\uEADC"),
        Custom30 ("\uEADD"),
        Custom31 ("\uEADE"),
        Custom32 ("\uEADF"),
        Custom33 ("\uEAE0"),
        Custom34 ("\uEAE1"),
        Custom35 ("\uEAE2"),
        Custom36 ("\uEAE3"),
        Custom37 ("\uEAE4"),
        Custom38 ("\uEAE5"),
        Custom39 ("\uEAE6"),
        Custom4 ("\uEAE7"),
        Custom40 ("\uEAE8"),
        Custom41 ("\uEAE9"),
        Custom42 ("\uEAEA"),
        Custom43 ("\uEAEB"),
        Custom44 ("\uEAEC"),
        Custom45 ("\uEAED"),
        Custom46 ("\uEAEE"),
        Custom47 ("\uEAEF"),
        Custom48 ("\uEAF0"),
        Custom49 ("\uEAF1"),
        Custom5 ("\uEAF2"),
        Custom50 ("\uEAF3"),
        Custom51 ("\uEAF4"),
        Custom52 ("\uEAF5"),
        Custom53 ("\uEAF6"),
        Custom54 ("\uEAF7"),
        Custom55 ("\uEAF8"),
        Custom56 ("\uEAF9"),
        Custom57 ("\uEAFA"),
        Custom58 ("\uEAFB"),
        Custom59 ("\uEAFC"),
        Custom6 ("\uEAFD"),
        Custom60 ("\uEAFE"),
        Custom61 ("\uEAFF"),
        Custom62 ("\uEB00"),
        Custom63 ("\uEB01"),
        Custom64 ("\uEB02"),
        Custom65 ("\uEB03"),
        Custom66 ("\uEB04"),
        Custom67 ("\uEB05"),
        Custom68 ("\uEB06"),
        Custom69 ("\uEB07"),
        Custom7 ("\uEB08"),
        Custom70 ("\uEB09"),
        Custom71 ("\uEB0A"),
        Custom72 ("\uEB0B"),
        Custom73 ("\uEB0C"),
        Custom74 ("\uEB0D"),
        Custom75 ("\uEB0E"),
        Custom76 ("\uEB0F"),
        Custom77 ("\uEB10"),
        Custom78 ("\uEB11"),
        Custom79 ("\uEB12"),
        Custom8 ("\uEB13"),
        Custom80 ("\uEB14"),
        Custom81 ("\uEB15"),
        Custom82 ("\uEB16"),
        Custom83 ("\uEB17"),
        Custom84 ("\uEB18"),
        Custom85 ("\uEB19"),
        Custom86 ("\uEB1A"),
        Custom87 ("\uEB1B"),
        Custom88 ("\uEB1C"),
        Custom89 ("\uEB1D"),
        Custom9 ("\uEB1E"),
        Custom90 ("\uEB1F"),
        Custom91 ("\uEB20"),
        Custom92 ("\uEB21"),
        Custom93 ("\uEB22"),
        Custom94 ("\uEB23"),
        Custom95 ("\uEB24"),
        Custom96 ("\uEB25"),
        Custom97 ("\uEB26"),
        Custom98 ("\uEB27"),
        Custom99 ("\uEB28");

        final String value;
        CustomIcons(String value) { this.value = value; }
    }

    public enum StandardIcons {
        StandardAccount ("\uEB29"),
        StandardActionListComponent ("\uEB2A"),
        StandardAddress ("\uEB2B"),
        StandardAll ("\uEB2C"),
        StandardAnnouncement ("\uEB2D"),
        StandardAnswerBest ("\uEB2E"),
        StandardAnswerPrivate ("\uEB2F"),
        StandardAnswerPublic ("\uEB30"),
        StandardApex ("\uEB31"),
        StandardApexPlugin ("\uEB32"),
        StandardApproval ("\uEB33"),
        StandardApps ("\uEB34"),
        StandardAppsAdmin ("\uEB35"),
        StandardArticle ("\uEB36"),
        StandardAssetRelationship ("\uEB37"),
        StandardAssignedResource ("\uEB38"),
        StandardAssignment ("\uEB39"),
        StandardAvatar ("\uEB3A"),
        StandardAvatarLoading ("\uEB3B"),
        StandardBot ("\uEB3C"),
        StandardBotTraining ("\uEB3D"),
        StandardBrand ("\uEB3E"),
        StandardBusinessHours ("\uEB3F"),
        StandardCalibration ("\uEB40"),
        StandardCall ("\uEB41"),
        StandardCallHistory ("\uEB42"),
        StandardCampaign ("\uEB43"),
        StandardCampaignMembers ("\uEB44"),
        StandardCanvas ("\uEB45"),
        StandardCarousel ("\uEB46"),
        StandardCase ("\uEB47"),
        StandardCaseChangeStatus ("\uEB48"),
        StandardCaseComment ("\uEB49"),
        StandardCaseEmail ("\uEB4A"),
        StandardCaseLogACall ("\uEB4B"),
        StandardCaseMilestone ("\uEB4C"),
        StandardCaseTranscript ("\uEB4D"),
        StandardChannelProgramHistory ("\uEB4E"),
        StandardChannelProgramLevels ("\uEB4F"),
        StandardChannelProgramMembers ("\uEB50"),
        StandardChannelPrograms ("\uEB51"),
        StandardChoice ("\uEB52"),
        StandardClient ("\uEB53"),
        StandardCms ("\uEB54"),
        StandardCoaching ("\uEB55"),
        StandardCollectionVariable ("\uEB56"),
        StandardConnectedApps ("\uEB57"),
        StandardConstant ("\uEB58"),
        StandardContact ("\uEB59"),
        StandardContactList ("\uEB5A"),
        StandardContactRequest ("\uEB5B"),
        StandardContract ("\uEB5C"),
        StandardContractLineItem ("\uEB5D"),
        StandardCurrency ("\uEB5E"),
        StandardCurrencyInput ("\uEB5F"),
        StandardCustom ("\uEB60"),
        StandardCustomNotification ("\uEB61"),
        StandardCustomerPortalUsers ("\uEB62"),
        StandardCustomers ("\uEB63"),
        StandardDashboard ("\uEB64"),
        StandardDataIntegrationHub ("\uEB65"),
        StandardDatadotcom ("\uEB66"),
        StandardDateInput ("\uEB67"),
        StandardDateTime ("\uEB68"),
        StandardDecision ("\uEB69"),
        StandardDefault ("\uEB6A"),
        StandardDisplayRichText ("\uEB6B"),
        StandardDisplayText ("\uEB6C"),
        StandardDocument ("\uEB6D"),
        StandardDrafts ("\uEB6E"),
        StandardDynamicRecordChoice ("\uEB6F"),
        StandardEmail ("\uEB70"),
        StandardEmailChatter ("\uEB71"),
        StandardEmpty ("\uEB72"),
        StandardEndorsement ("\uEB73"),
        StandardEntitlement ("\uEB74"),
        StandardEntitlementProcess ("\uEB75"),
        StandardEntitlementTemplate ("\uEB76"),
        StandardEntity ("\uEB77"),
        StandardEntityMilestone ("\uEB78"),
        StandardEnvironmentHub ("\uEB79"),
        StandardEvent ("\uEB7A"),
        StandardFeed ("\uEB7B"),
        StandardFeedback ("\uEB7C"),
        StandardFile ("\uEB7D"),
        StandardFlow ("\uEB7E"),
        StandardFolder ("\uEB7F"),
        StandardForecasts ("\uEB80"),
        StandardFormula ("\uEB81"),
        StandardGenericLoading ("\uEB82"),
        StandardGlobalConstant ("\uEB83"),
        StandardGoals ("\uEB84"),
        StandardGroupLoading ("\uEB85"),
        StandardGroups ("\uEB86"),
        StandardHierarchy ("\uEB87"),
        StandardHome ("\uEB88"),
        StandardHousehold ("\uEB89"),
        StandardIndividual ("\uEB8A"),
        StandardInsights ("\uEB8B"),
        StandardInvestmentAccount ("\uEB8C"),
        StandardIotContext ("\uEB8D"),
        StandardIotOrchestrations ("\uEB8E"),
        StandardKanban ("\uEB8F"),
        StandardKnowledge ("\uEB90"),
        StandardLead ("\uEB91"),
        StandardLeadInsights ("\uEB92"),
        StandardLeadList ("\uEB93"),
        StandardLightningComponent ("\uEB94"),
        StandardLightningUsage ("\uEB95"),
        StandardLink ("\uEB96"),
        StandardListEmail ("\uEB97"),
        StandardLiveChat ("\uEB98"),
        StandardLiveChatVisitor ("\uEB99"),
        StandardLocation ("\uEB9A"),
        StandardLogACall ("\uEB9B"),
        StandardLogging ("\uEB9C"),
        StandardLoop ("\uEB9D"),
        StandardMacros ("\uEB9E"),
        StandardMaintenanceAsset ("\uEB9F"),
        StandardMaintenancePlan ("\uEBA0"),
        StandardMarketingActions ("\uEBA1"),
        StandardMerge ("\uEBA2"),
        StandardMessagingConversation ("\uEBA3"),
        StandardMessagingSession ("\uEBA4"),
        StandardMessagingUser ("\uEBA5"),
        StandardMetrics ("\uEBA6"),
        StandardMultiPicklist ("\uEBA7"),
        StandardMultiSelectCheckbox ("\uEBA8"),
        StandardNews ("\uEBA9"),
        StandardNote ("\uEBAA"),
        StandardNumberInput ("\uEBAB"),
        StandardOmniSupervisor ("\uEBAC"),
        StandardOperatingHours ("\uEBAD"),
        StandardOpportunity ("\uEBAE"),
        StandardOpportunitySplits ("\uEBAF"),
        StandardOrders ("\uEBB0"),
        StandardOutcome ("\uEBB1"),
        StandardPartnerFundAllocation ("\uEBB2"),
        StandardPartnerFundClaim ("\uEBB3"),
        StandardPartnerFundRequest ("\uEBB4"),
        StandardPartnerMarketingBudget ("\uEBB5"),
        StandardPartners ("\uEBB6"),
        StandardPassword ("\uEBB7"),
        StandardPastChat ("\uEBB8"),
        StandardPeople ("\uEBB9"),
        StandardPerformance ("\uEBBA"),
        StandardPersonAccount ("\uEBBB"),
        StandardPhoto ("\uEBBC"),
        StandardPicklistChoice ("\uEBBD"),
        StandardPicklistType ("\uEBBE"),
        StandardPoll ("\uEBBF"),
        StandardPortal ("\uEBC0"),
        StandardPortalRoles ("\uEBC1"),
        StandardPortalRolesAndSubordinates ("\uEBC2"),
        StandardPost ("\uEBC3"),
        StandardPricebook ("\uEBC4"),
        StandardProcess ("\uEBC5"),
        StandardProduct ("\uEBC6"),
        StandardProductConsumed ("\uEBC7"),
        StandardProductItem ("\uEBC8"),
        StandardProductItemTransaction ("\uEBC9"),
        StandardProductRequest ("\uEBCA"),
        StandardProductRequestLineItem ("\uEBCB"),
        StandardProductRequired ("\uEBCC"),
        StandardProductTransfer ("\uEBCD"),
        StandardProposition ("\uEBCE"),
        StandardQuestionBest ("\uEBCF"),
        StandardQuestionFeed ("\uEBD0"),
        StandardQueue ("\uEBD1"),
        StandardQuickText ("\uEBD2"),
        StandardQuip ("\uEBD3"),
        StandardQuipSheet ("\uEBD4"),
        StandardQuotes ("\uEBD5"),
        StandardRadioButton ("\uEBD6"),
        StandardReadReceipts ("\uEBD7"),
        StandardRecent ("\uEBD8"),
        StandardRecord ("\uEBD9"),
        StandardRecordCreate ("\uEBDA"),
        StandardRecordDelete ("\uEBDB"),
        StandardRecordLookup ("\uEBDC"),
        StandardRecordUpdate ("\uEBDD"),
        StandardRelatedList ("\uEBDE"),
        StandardRelationship ("\uEBDF"),
        StandardReport ("\uEBE0"),
        StandardResourceAbsence ("\uEBE1"),
        StandardResourceCapacity ("\uEBE2"),
        StandardResourcePreference ("\uEBE3"),
        StandardResourceSkill ("\uEBE4"),
        StandardReturnOrder ("\uEBE5"),
        StandardReturnOrderLineItem ("\uEBE6"),
        StandardReward ("\uEBE7"),
        StandardRtcPresence ("\uEBE8"),
        StandardSalesPath ("\uEBE9"),
        StandardScanCard ("\uEBEA"),
        StandardScreen ("\uEBEB"),
        StandardSearch ("\uEBEC"),
        StandardServiceAppointment ("\uEBED"),
        StandardServiceAppointmentCapacityUsage ("\uEBEE"),
        StandardServiceContract ("\uEBEF"),
        StandardServiceCrew ("\uEBF0"),
        StandardServiceCrewMember ("\uEBF1"),
        StandardServiceReport ("\uEBF2"),
        StandardServiceResource ("\uEBF3"),
        StandardServiceTerritory ("\uEBF4"),
        StandardServiceTerritoryLocation ("\uEBF5"),
        StandardServiceTerritoryMember ("\uEBF6"),
        StandardShipment ("\uEBF7"),
        StandardSkill ("\uEBF8"),
        StandardSkillEntity ("\uEBF9"),
        StandardSkillRequirement ("\uEBFA"),
        StandardSms ("\uEBFB"),
        StandardSnippet ("\uEBFC"),
        StandardSobject ("\uEBFD"),
        StandardSobjectCollection ("\uEBFE"),
        StandardSocial ("\uEBFF"),
        StandardSolution ("\uEC00"),
        StandardSossession ("\uEC01"),
        StandardStage ("\uEC02"),
        StandardStageCollection ("\uEC03"),
        StandardSteps ("\uEC04"),
        StandardStrategy ("\uEC05"),
        StandardSurvey ("\uEC06"),
        StandardSystemAndGlobalVariable ("\uEC07"),
        StandardTask ("\uEC08"),
        StandardTask2 ("\uEC09"),
        StandardTeamMember ("\uEC0A"),
        StandardTemplate ("\uEC0B"),
        StandardText ("\uEC0C"),
        StandardTextTemplate ("\uEC0D"),
        StandardTextarea ("\uEC0E"),
        StandardTextbox ("\uEC0F"),
        StandardThanks ("\uEC10"),
        StandardThanksLoading ("\uEC11"),
        StandardTimesheet ("\uEC12"),
        StandardTimesheetEntry ("\uEC13"),
        StandardTimeslot ("\uEC14"),
        StandardToday ("\uEC15"),
        StandardTopic ("\uEC16"),
        StandardTopic2 ("\uEC17"),
        StandardTrailhead ("\uEC18"),
        StandardUnmatched ("\uEC19"),
        StandardUser ("\uEC1A"),
        StandardVariable ("\uEC1B"),
        StandardWaits ("\uEC1C"),
        StandardWorkCapacityLimit ("\uEC1D"),
        StandardWorkCapacityUsage ("\uEC1E"),
        StandardWorkOrder ("\uEC1F"),
        StandardWorkOrderItem ("\uEC20"),
        StandardWorkQueue ("\uEC21"),
        StandardWorkType ("\uEC22"),
        StandardWorkTypeGroup ("\uEC23");

        final String value;
        StandardIcons(String value) { this.value = value; }
    }

    public enum UtilityIcons {
        UtilityActivity ("\uEC24"),
        UtilityAdSet ("\uEC25"),
        UtilityAdd ("\uEC26"),
        UtilityAdduser ("\uEC27"),
        UtilityAdvancedFunction ("\uEC28"),
        UtilityAdvertising ("\uEC29"),
        UtilityAll ("\uEC2A"),
        UtilityAnchor ("\uEC2B"),
        UtilityAnimalAndNature ("\uEC2C"),
        UtilityAnnouncement ("\uEC2D"),
        UtilityAnswer ("\uEC2E"),
        UtilityAnsweredTwice ("\uEC2F"),
        UtilityApex ("\uEC30"),
        UtilityApexPlugin ("\uEC31"),
        UtilityApproval ("\uEC32"),
        UtilityApps ("\uEC33"),
        UtilityArchive ("\uEC34"),
        UtilityArrowdown ("\uEC35"),
        UtilityArrowup ("\uEC36"),
        UtilityAssignment ("\uEC37"),
        UtilityAttach ("\uEC38"),
        UtilityAutomate ("\uEC39"),
        UtilityBack ("\uEC3A"),
        UtilityBan ("\uEC3B"),
        UtilityBlockVisitor ("\uEC3C"),
        UtilityBold ("\uEC3D"),
        UtilityBookmark ("\uEC3E"),
        UtilityBreadcrumbs ("\uEC3F"),
        UtilityBroadcast ("\uEC40"),
        UtilityBrush ("\uEC41"),
        UtilityBucket ("\uEC42"),
        UtilityBuilder ("\uEC43"),
        UtilityCall ("\uEC44"),
        UtilityCampaign ("\uEC45"),
        UtilityCancelFileRequest ("\uEC46"),
        UtilityCancelTransfer ("\uEC47"),
        UtilityCapslock ("\uEC48"),
        UtilityCart ("\uEC49"),
        UtilityCase ("\uEC4A"),
        UtilityCases ("\uEC4B"),
        UtilityCenterAlignText ("\uEC4C"),
        UtilityChangeOwner ("\uEC4D"),
        UtilityChangeRecordType ("\uEC4E"),
        UtilityChart ("\uEC4F"),
        UtilityChat ("\uEC50"),
        UtilityCheck ("\uEC51"),
        UtilityCheckin ("\uEC52"),
        UtilityChevrondown ("\uEC53"),
        UtilityChevronleft ("\uEC54"),
        UtilityChevronright ("\uEC55"),
        UtilityChevronup ("\uEC56"),
        UtilityChoice ("\uEC57"),
        UtilityClassicInterface ("\uEC58"),
        UtilityClear ("\uEC59"),
        UtilityClock ("\uEC5A"),
        UtilityClose ("\uEC5B"),
        UtilityCollapseAll ("\uEC5C"),
        UtilityCollectionVariable ("\uEC5D"),
        UtilityColorSwatch ("\uEC5E"),
        UtilityComments ("\uEC5F"),
        UtilityCompany ("\uEC60"),
        UtilityConnectedApps ("\uEC61"),
        UtilityConstant ("\uEC62"),
        UtilityContactRequest ("\uEC63"),
        UtilityContract ("\uEC64"),
        UtilityContractAlt ("\uEC65"),
        UtilityCopy ("\uEC66"),
        UtilityCopyToClipboard ("\uEC67"),
        UtilityCrossfilter ("\uEC68"),
        UtilityCurrency ("\uEC69"),
        UtilityCurrencyInput ("\uEC6A"),
        UtilityCustomApps ("\uEC6B"),
        UtilityCut ("\uEC6C"),
        UtilityDash ("\uEC6D"),
        UtilityDatabase ("\uEC6E"),
        UtilityDatadotcom ("\uEC6F"),
        UtilityDateInput ("\uEC70"),
        UtilityDateTime ("\uEC71"),
        UtilityDayview ("\uEC72"),
        UtilityDelete ("\uEC73"),
        UtilityDeprecate ("\uEC74"),
        UtilityDescription ("\uEC75"),
        UtilityDesktop ("\uEC76"),
        UtilityDesktopConsole ("\uEC77"),
        UtilityDialing ("\uEC78"),
        UtilityDislike ("\uEC79"),
        UtilityDisplayRichText ("\uEC7A"),
        UtilityDisplayText ("\uEC7B"),
        UtilityDockPanel ("\uEC7C"),
        UtilityDown ("\uEC7D"),
        UtilityDownload ("\uEC7E"),
        UtilityDrag ("\uEC7F"),
        UtilityDragAndDrop ("\uEC80"),
        UtilityDynamicRecordChoice ("\uEC81"),
        UtilityEdit ("\uEC82"),
        UtilityEditForm ("\uEC83"),
        UtilityEinstein ("\uEC84"),
        UtilityEmail ("\uEC85"),
        UtilityEmailOpen ("\uEC86"),
        UtilityEmoji ("\uEC87"),
        UtilityEndCall ("\uEC88"),
        UtilityEndChat ("\uEC89"),
        UtilityEndMessagingSession ("\uEC8A"),
        UtilityErectWindow ("\uEC8B"),
        UtilityError ("\uEC8C"),
        UtilityEvent ("\uEC8D"),
        UtilityEvents ("\uEC8E"),
        UtilityExpand ("\uEC8F"),
        UtilityExpandAll ("\uEC90"),
        UtilityExpandAlt ("\uEC91"),
        UtilityFallback ("\uEC92"),
        UtilityFavorite ("\uEC93"),
        UtilityFeed ("\uEC94"),
        UtilityFile ("\uEC95"),
        UtilityFilter ("\uEC96"),
        UtilityFilterList ("\uEC97"),
        UtilityFlow ("\uEC98"),
        UtilityFoodAndDrink ("\uEC99"),
        UtilityFormula ("\uEC9A"),
        UtilityForward ("\uEC9B"),
        UtilityForwardUp ("\uEC9C"),
        UtilityFrozen ("\uEC9D"),
        UtilityFullWidthView ("\uEC9E"),
        UtilityGlobalConstant ("\uEC9F"),
        UtilityGraph ("\uECA0"),
        UtilityGroups ("\uECA1"),
        UtilityHelp ("\uECA2"),
        UtilityHelpCenter ("\uECA3"),
        UtilityHide ("\uECA4"),
        UtilityHierarchy ("\uECA5"),
        UtilityHome ("\uECA6"),
        UtilityIdentity ("\uECA7"),
        UtilityImage ("\uECA8"),
        UtilityInbox ("\uECA9"),
        UtilityIncomingCall ("\uECAA"),
        UtilityInfo ("\uECAB"),
        UtilityInfoAlt ("\uECAC"),
        UtilityInsertTagField ("\uECAD"),
        UtilityInsertTemplate ("\uECAE"),
        UtilityInspectorPanel ("\uECAF"),
        UtilityInternalShare ("\uECB0"),
        UtilityItalic ("\uECB1"),
        UtilityJumpToBottom ("\uECB2"),
        UtilityJumpToTop ("\uECB3"),
        UtilityJustifyText ("\uECB4"),
        UtilityKanban ("\uECB5"),
        UtilityKeyboardDismiss ("\uECB6"),
        UtilityKnowledgeBase ("\uECB7"),
        UtilityLayers ("\uECB8"),
        UtilityLayout ("\uECB9"),
        UtilityLeaveConference ("\uECBA"),
        UtilityLeft ("\uECBB"),
        UtilityLeftAlignText ("\uECBC"),
        UtilityLevelDown ("\uECBD"),
        UtilityLevelUp ("\uECBE"),
        UtilityLightBulb ("\uECBF"),
        UtilityLike ("\uECC0"),
        UtilityLink ("\uECC1"),
        UtilityLinked ("\uECC2"),
        UtilityList ("\uECC3"),
        UtilityListen ("\uECC4"),
        UtilityLiveMessage ("\uECC5"),
        UtilityLocation ("\uECC6"),
        UtilityLock ("\uECC7"),
        UtilityLogACall ("\uECC8"),
        UtilityLogout ("\uECC9"),
        UtilityLoop ("\uECCA"),
        UtilityLowerFlag ("\uECCB"),
        UtilityMacros ("\uECCC"),
        UtilityMagicwand ("\uECCD"),
        UtilityMarkAllAsRead ("\uECCE"),
        UtilityMatrix ("\uECCF"),
        UtilityMerge ("\uECD0"),
        UtilityMergeField ("\uECD1"),
        UtilityMetrics ("\uECD2"),
        UtilityMinimizeWindow ("\uECD3"),
        UtilityMissedCall ("\uECD4"),
        UtilityMoney ("\uECD5"),
        UtilityMoneybag ("\uECD6"),
        UtilityMonthlyview ("\uECD7"),
        UtilityMove ("\uECD8"),
        UtilityMultiPicklist ("\uECD9"),
        UtilityMultiSelectCheckbox ("\uECDA"),
        UtilityMuted ("\uECDB"),
        UtilityNew ("\uECDC"),
        UtilityNewDirectMessage ("\uECDD"),
        UtilityNewWindow ("\uECDE"),
        UtilityNews ("\uECDF"),
        UtilityNote ("\uECE0"),
        UtilityNotebook ("\uECE1"),
        UtilityNotification ("\uECE2"),
        UtilityNumberInput ("\uECE3"),
        UtilityOffice365 ("\uECE4"),
        UtilityOffline ("\uECE5"),
        UtilityOfflineCached ("\uECE6"),
        UtilityOmniChannel ("\uECE7"),
        UtilityOpen ("\uECE8"),
        UtilityOpenFolder ("\uECE9"),
        UtilityOpenedFolder ("\uECEA"),
        UtilityOutboundCall ("\uECEB"),
        UtilityOutcome ("\uECEC"),
        UtilityOverflow ("\uECED"),
        UtilityPackage ("\uECEE"),
        UtilityPackageOrg ("\uECEF"),
        UtilityPackageOrgBeta ("\uECF0"),
        UtilityPage ("\uECF1"),
        UtilityPalette ("\uECF2"),
        UtilityPassword ("\uECF3"),
        UtilityPaste ("\uECF4"),
        UtilityPause ("\uECF5"),
        UtilityPeople ("\uECF6"),
        UtilityPhoneLandscape ("\uECF7"),
        UtilityPhonePortrait ("\uECF8"),
        UtilityPhoto ("\uECF9"),
        UtilityPicklist ("\uECFA"),
        UtilityPicklistChoice ("\uECFB"),
        UtilityPicklistType ("\uECFC"),
        UtilityPin ("\uECFD"),
        UtilityPinned ("\uECFE"),
        UtilityPlay ("\uECFF"),
        UtilityPodcastWebinar ("\uED00"),
        UtilityPopIn ("\uED01"),
        UtilityPower ("\uED02"),
        UtilityPreview ("\uED03"),
        UtilityPrint ("\uED04"),
        UtilityPriority ("\uED05"),
        UtilityPrivatelyShared ("\uED06"),
        UtilityProcess ("\uED07"),
        UtilityPush ("\uED08"),
        UtilityPuzzle ("\uED09"),
        UtilityQuestion ("\uED0A"),
        UtilityQuestionMark ("\uED0B"),
        UtilityQuestionsAndAnswers ("\uED0C"),
        UtilityQuickText ("\uED0D"),
        UtilityQuotationMarks ("\uED0E"),
        UtilityRadioButton ("\uED0F"),
        UtilityRating ("\uED10"),
        UtilityReassign ("\uED11"),
        UtilityRecord ("\uED12"),
        UtilityRecordCreate ("\uED13"),
        UtilityRecordDelete ("\uED14"),
        UtilityRecordLookup ("\uED15"),
        UtilityRecordUpdate ("\uED16"),
        UtilityRecurringException ("\uED17"),
        UtilityRedo ("\uED18"),
        UtilityRefresh ("\uED19"),
        UtilityRelate ("\uED1A"),
        UtilityReminder ("\uED1B"),
        UtilityRemoveFormatting ("\uED1C"),
        UtilityRemoveLink ("\uED1D"),
        UtilityReplace ("\uED1E"),
        UtilityReply ("\uED1F"),
        UtilityReplyAll ("\uED20"),
        UtilityResetPassword ("\uED21"),
        UtilityResourceAbsence ("\uED22"),
        UtilityResourceCapacity ("\uED23"),
        UtilityResourceTerritory ("\uED24"),
        UtilityRetweet ("\uED25"),
        UtilityRichtextbulletedlist ("\uED26"),
        UtilityRichtextindent ("\uED27"),
        UtilityRichtextnumberedlist ("\uED28"),
        UtilityRichtextoutdent ("\uED29"),
        UtilityRight ("\uED2A"),
        UtilityRightAlignText ("\uED2B"),
        UtilityRotate ("\uED2C"),
        UtilityRows ("\uED2D"),
        UtilityRules ("\uED2E"),
        UtilitySalesforce1 ("\uED2F"),
        UtilitySave ("\uED30"),
        UtilityScreen ("\uED31"),
        UtilitySearch ("\uED32"),
        UtilitySend ("\uED33"),
        UtilitySentimentNegative ("\uED34"),
        UtilitySentimentNeutral ("\uED35"),
        UtilitySettings ("\uED36"),
        UtilitySetup ("\uED37"),
        UtilitySetupAssistantGuide ("\uED38"),
        UtilityShare ("\uED39"),
        UtilityShareFile ("\uED3A"),
        UtilityShareMobile ("\uED3B"),
        UtilitySharePost ("\uED3C"),
        UtilityShield ("\uED3D"),
        UtilityShoppingBag ("\uED3E"),
        UtilityShortcuts ("\uED3F"),
        UtilitySideList ("\uED40"),
        UtilitySignpost ("\uED41"),
        UtilitySmileyAndPeople ("\uED42"),
        UtilitySms ("\uED43"),
        UtilitySnippet ("\uED44"),
        UtilitySobject ("\uED45"),
        UtilitySobjectCollection ("\uED46"),
        UtilitySocialshare ("\uED47"),
        UtilitySort ("\uED48"),
        UtilitySpinner ("\uED49"),
        UtilityStage ("\uED4A"),
        UtilityStageCollection ("\uED4B"),
        UtilityStandardObjects ("\uED4C"),
        UtilitySteps ("\uED4D"),
        UtilityStop ("\uED4E"),
        UtilityStrategy ("\uED4F"),
        UtilityStrikethrough ("\uED50"),
        UtilitySuccess ("\uED51"),
        UtilitySummary ("\uED52"),
        UtilitySummarydetail ("\uED53"),
        UtilitySurvey ("\uED54"),
        UtilitySwitch ("\uED55"),
        UtilitySymbols ("\uED56"),
        UtilitySync ("\uED57"),
        UtilitySystemAndGlobalVariable ("\uED58"),
        UtilityTable ("\uED59"),
        UtilityTabletLandscape ("\uED5A"),
        UtilityTabletPortrait ("\uED5B"),
        UtilityTabset ("\uED5C"),
        UtilityTask ("\uED5D"),
        UtilityText ("\uED5E"),
        UtilityTextBackgroundColor ("\uED5F"),
        UtilityTextColor ("\uED60"),
        UtilityTextTemplate ("\uED61"),
        UtilityTextarea ("\uED62"),
        UtilityTextbox ("\uED63"),
        UtilityThreedots ("\uED64"),
        UtilityThreedotsVertical ("\uED65"),
        UtilityThunder ("\uED66"),
        UtilityTileCardList ("\uED67"),
        UtilityTogglePanelBottom ("\uED68"),
        UtilityTogglePanelLeft ("\uED69"),
        UtilityTogglePanelRight ("\uED6A"),
        UtilityTogglePanelTop ("\uED6B"),
        UtilityTopic ("\uED6C"),
        UtilityTopic2 ("\uED6D"),
        UtilityTouchAction ("\uED6E"),
        UtilityTracker ("\uED6F"),
        UtilityTrail ("\uED70"),
        UtilityTrailhead ("\uED71"),
        UtilityTravelAndPlaces ("\uED72"),
        UtilityTrending ("\uED73"),
        UtilityTurnOffNotifications ("\uED74"),
        UtilityType ("\uED75"),
        UtilityTypeTool ("\uED76"),
        UtilityUndelete ("\uED77"),
        UtilityUndeprecate ("\uED78"),
        UtilityUnderline ("\uED79"),
        UtilityUndo ("\uED7A"),
        UtilityUnlinked ("\uED7B"),
        UtilityUnlock ("\uED7C"),
        UtilityUnmuted ("\uED7D"),
        UtilityUp ("\uED7E"),
        UtilityUpload ("\uED7F"),
        UtilityUser ("\uED80"),
        UtilityUserRole ("\uED81"),
        UtilityVariable ("\uED82"),
        UtilityVideo ("\uED83"),
        UtilityVoicemailDrop ("\uED84"),
        UtilityVolumeHigh ("\uED85"),
        UtilityVolumeLow ("\uED86"),
        UtilityVolumeOff ("\uED87"),
        UtilityWaits ("\uED88"),
        UtilityWarning ("\uED89"),
        UtilityWeeklyview ("\uED8A"),
        UtilityWifi ("\uED8B"),
        UtilityWorkOrderType ("\uED8C"),
        UtilityWorld ("\uED8D"),
        UtilityYubiKey ("\uED8E"),
        UtilityZoomin ("\uED8F"),
        UtilityZoomout ("\uED90");

        final String value;
        UtilityIcons(String value) { this.value = value; }
    }


}
